name: rust-next

permissions:
  contents: read

on:
  schedule:
  - cron: '8 8 8 * *'

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        rust: ["stable", "beta"]
        include:
        - os: ubuntu-latest
          rust: "nightly"
    continue-on-error: ${{ matrix.rust != 'stable' }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}
    - uses: Swatinem/rust-cache@v2
    - name: Build Debug
      run: cargo test --no-run
    - name: Test Debug
      run: cargo test
    - name: Build Release
      run: cargo test --no-run --release
    - name: Test Release
      run: cargo test --release
  latest:
    name: "Check latest dependencies"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - uses: Swatinem/rust-cache@v2
    - name: Update dependencues
      run: cargo update
    - name: Build Debug
      run: cargo test --no-run
    - name: Test Debug
      run: cargo test
    - name: Build Release
      run: cargo test --no-run --release
    - name: Test Release
      run: cargo test --release
